name: earthaccess-dev
channels:
  - conda-forge
dependencies:
  # This environment bootstraps pip, the actual dev environment
  # is installed and managed with pip
  - python=3.10

  - pip
  - pip:
      - --editable .[dev]
