name: earthdata-dev
channels:
- conda-forge
dependencies:
- python=3.9
- jupyterlab=3
- xarray>=0.19
- rioxarray>=0.3
- matplotlib-base>=3.3
- cartopy>=0.18.0
- ipyleaflet>=0.13
- netcdf4>=1.5
- h5netcdf>=0.11
- h5py>=3.2
- geopandas>=0.9
- zarr>=2.9.5
- s3fs
- dask
- pip
- pip:
    - pqdm
    - zarr-eosdis-store
    - earthdata
