name: Documentation

on:
  push:
    branches:
      - main
      - documentation
    paths:
      - earthaccess/**
      - tests/**
      - docs/**
      - notebooks/**
      - .github/workflows/documentation.yml
  pull_request:
    paths:
      - earthaccess/**
      - tests/**
      - docs/**
      - notebooks/**
      - .github/workflows/documentation.yml
    types: [opened, synchronize]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Set up cache
        uses: actions/cache@v1
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - name: Install Dependencies
        run: poetry install
      - name: Build docs
        run: poetry run bash scripts/build-docs.sh
        env:
          EARTHDATA_USERNAME: ${{ secrets.EDL_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EDL_PASSWORD }}

      - name: Deploy
        if: |
          github.event_name == 'push'
          && (github.ref == 'refs/heads/main' || github.ref == 'ref/heads/documentation')
          && github.repository == 'nsidc/earthaccess'
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
