name: Publish
on:
  push:
    branch:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify version matches git tag
        run: scripts/verify_tag.sh
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
